import { useState } from "react";
import { useNavigate, Link } from "react-router-dom";
import { 
  CreditCard, 
  Truck, 
  Building2, 
  ArrowLeft,
  Loader2,
  ShieldCheck,
  CheckCircle
} from "lucide-react";
import Layout from "@/components/layout/Layout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { useCart } from "@/contexts/CartContext";
import { useAuth } from "@/contexts/AuthContext";
import { supabase } from "@/integrations/supabase/client";
import { formatPrice } from "@/lib/formatPrice";
import { toast } from "sonner";

type PaymentMethod = "cash_on_delivery" | "bank_transfer";

const Checkout = () => {
  const navigate = useNavigate();
  const { items, getSubtotal, clearCart } = useCart();
  const { user, profile } = useAuth();
  const [loading, setLoading] = useState(false);
  const [orderPlaced, setOrderPlaced] = useState(false);
  const [orderNumber, setOrderNumber] = useState("");

  const [formData, setFormData] = useState({
    customer_name: profile?.full_name || "",
    customer_email: user?.email || "",
    customer_phone: profile?.phone || "",
    company_name: profile?.company_name || "",
    shipping_address: profile?.shipping_address || "",
    shipping_city: profile?.shipping_city || "",
    shipping_postal_code: profile?.shipping_postal_code || "",
    notes: "",
    payment_method: "cash_on_delivery" as PaymentMethod,
  });

  const subtotal = getSubtotal();
  const shippingCost = subtotal >= 10000 ? 0 : 150;
  const total = subtotal + shippingCost;

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!user) {
      toast.error("অর্ডার দিতে লগইন করুন");
      navigate("/account");
      return;
    }

    if (items.length === 0) {
      toast.error("কার্ট খালি");
      return;
    }

    setLoading(true);

    try {
      // Create order - order_number is auto-generated by trigger
      const orderData = {
        user_id: user.id,
        status: "pending_payment" as const,
        payment_method: formData.payment_method as "cash_on_delivery" | "bank_transfer" | "online_payment",
        subtotal,
        shipping_cost: shippingCost,
        total,
        customer_name: formData.customer_name,
        customer_email: formData.customer_email,
        customer_phone: formData.customer_phone,
        company_name: formData.company_name || null,
        shipping_address: formData.shipping_address,
        shipping_city: formData.shipping_city,
        shipping_postal_code: formData.shipping_postal_code || null,
        notes: formData.notes || null,
        order_number: `STI-${Date.now()}`, // Temporary, will be overwritten by trigger
      };

      const { data: order, error: orderError } = await supabase
        .from("orders")
        .insert([orderData])
        .select()
        .single();

      if (orderError) throw orderError;

      // Create order items
      const orderItems = items.map((item) => ({
        order_id: order.id,
        product_id: item.id,
        product_name: item.name,
        product_sku: item.sku,
        quantity: item.quantity,
        unit_price: item.price,
        total_price: item.price * item.quantity,
      }));

      const { error: itemsError } = await supabase
        .from("order_items")
        .insert(orderItems);

      if (itemsError) throw itemsError;

      // Success
      setOrderNumber(order.order_number);
      setOrderPlaced(true);
      clearCart();
      toast.success("অর্ডার সফলভাবে জমা হয়েছে!");
    } catch (error) {
      console.error("Order error:", error);
      toast.error("অর্ডার জমা দিতে সমস্যা হয়েছে। আবার চেষ্টা করুন।");
    } finally {
      setLoading(false);
    }
  };

  if (!user) {
    return (
      <Layout>
        <div className="container-premium py-16 text-center">
          <h1 className="text-2xl font-bold mb-4">লগইন করুন</h1>
          <p className="text-muted-foreground mb-6">অর্ডার দিতে আপনাকে লগইন করতে হবে</p>
          <Button onClick={() => navigate("/account")}>লগইন করুন</Button>
        </div>
      </Layout>
    );
  }

  if (orderPlaced) {
    return (
      <Layout>
        <div className="container-premium py-16 md:py-24">
          <div className="max-w-lg mx-auto text-center">
            <div className="w-20 h-20 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-6">
              <CheckCircle className="h-10 w-10 text-green-600" />
            </div>
            <h1 className="text-2xl md:text-3xl font-bold mb-4">অর্ডার সফল হয়েছে!</h1>
            <p className="text-muted-foreground mb-2">
              আপনার অর্ডার নম্বর:
            </p>
            <p className="text-xl font-bold text-primary mb-6">{orderNumber}</p>
            <p className="text-muted-foreground mb-8">
              আমরা শীঘ্রই আপনার সাথে যোগাযোগ করব। ধন্যবাদ!
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button onClick={() => navigate("/account")}>
                অর্ডার দেখুন
              </Button>
              <Button variant="outline" onClick={() => navigate("/categories")}>
                আরও কেনাকাটা করুন
              </Button>
            </div>
          </div>
        </div>
      </Layout>
    );
  }

  if (items.length === 0) {
    return (
      <Layout>
        <div className="container-premium py-16 text-center">
          <h1 className="text-2xl font-bold mb-4">কার্ট খালি</h1>
          <p className="text-muted-foreground mb-6">চেকআউটের জন্য পণ্য যোগ করুন</p>
          <Button onClick={() => navigate("/categories")}>পণ্য দেখুন</Button>
        </div>
      </Layout>
    );
  }

  return (
    <Layout>
      <section className="bg-muted/50 border-b border-border">
        <div className="container-premium py-6 md:py-8">
          <Link to="/cart" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-primary mb-4">
            <ArrowLeft className="h-4 w-4" />
            কার্টে ফিরে যান
          </Link>
          <h1 className="text-2xl md:text-3xl font-bold">চেকআউট</h1>
        </div>
      </section>

      <section className="py-8 md:py-12">
        <div className="container-premium">
          <form onSubmit={handleSubmit}>
            <div className="grid lg:grid-cols-3 gap-8">
              {/* Form */}
              <div className="lg:col-span-2 space-y-8">
                {/* Contact Info */}
                <div className="bg-card border border-border rounded-lg p-6">
                  <h2 className="font-semibold text-lg mb-4">যোগাযোগের তথ্য</h2>
                  <div className="grid md:grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <Label htmlFor="customer_name">নাম *</Label>
                      <Input
                        id="customer_name"
                        value={formData.customer_name}
                        onChange={(e) => setFormData({ ...formData, customer_name: e.target.value })}
                        required
                      />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="company_name">কোম্পানির নাম</Label>
                      <Input
                        id="company_name"
                        value={formData.company_name}
                        onChange={(e) => setFormData({ ...formData, company_name: e.target.value })}
                      />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="customer_email">ইমেইল *</Label>
                      <Input
                        id="customer_email"
                        type="email"
                        value={formData.customer_email}
                        onChange={(e) => setFormData({ ...formData, customer_email: e.target.value })}
                        required
                      />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="customer_phone">ফোন *</Label>
                      <Input
                        id="customer_phone"
                        value={formData.customer_phone}
                        onChange={(e) => setFormData({ ...formData, customer_phone: e.target.value })}
                        placeholder="+880"
                        required
                      />
                    </div>
                  </div>
                </div>

                {/* Shipping Address */}
                <div className="bg-card border border-border rounded-lg p-6">
                  <h2 className="font-semibold text-lg mb-4 flex items-center gap-2">
                    <Truck className="h-5 w-5" />
                    ডেলিভারি ঠিকানা
                  </h2>
                  <div className="grid md:grid-cols-2 gap-4">
                    <div className="md:col-span-2 space-y-2">
                      <Label htmlFor="shipping_address">ঠিকানা *</Label>
                      <Input
                        id="shipping_address"
                        value={formData.shipping_address}
                        onChange={(e) => setFormData({ ...formData, shipping_address: e.target.value })}
                        placeholder="সড়ক, বাড়ি নম্বর, এলাকা"
                        required
                      />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="shipping_city">শহর *</Label>
                      <Input
                        id="shipping_city"
                        value={formData.shipping_city}
                        onChange={(e) => setFormData({ ...formData, shipping_city: e.target.value })}
                        placeholder="ঢাকা"
                        required
                      />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="shipping_postal_code">পোস্টাল কোড</Label>
                      <Input
                        id="shipping_postal_code"
                        value={formData.shipping_postal_code}
                        onChange={(e) => setFormData({ ...formData, shipping_postal_code: e.target.value })}
                        placeholder="1000"
                      />
                    </div>
                  </div>
                </div>

                {/* Payment Method */}
                <div className="bg-card border border-border rounded-lg p-6">
                  <h2 className="font-semibold text-lg mb-4 flex items-center gap-2">
                    <CreditCard className="h-5 w-5" />
                    পেমেন্ট পদ্ধতি
                  </h2>
                  <RadioGroup
                    value={formData.payment_method}
                    onValueChange={(value) => setFormData({ ...formData, payment_method: value as PaymentMethod })}
                    className="space-y-3"
                  >
                    <div className="flex items-center space-x-3 border border-border rounded-lg p-4 cursor-pointer hover:bg-muted/50 transition-colors">
                      <RadioGroupItem value="cash_on_delivery" id="cod" />
                      <Label htmlFor="cod" className="flex-1 cursor-pointer">
                        <div className="flex items-center gap-3">
                          <Truck className="h-5 w-5 text-primary" />
                          <div>
                            <p className="font-medium">ক্যাশ অন ডেলিভারি</p>
                            <p className="text-sm text-muted-foreground">পণ্য হাতে পেয়ে টাকা দিন</p>
                          </div>
                        </div>
                      </Label>
                    </div>
                    <div className="flex items-center space-x-3 border border-border rounded-lg p-4 cursor-pointer hover:bg-muted/50 transition-colors">
                      <RadioGroupItem value="bank_transfer" id="bank" />
                      <Label htmlFor="bank" className="flex-1 cursor-pointer">
                        <div className="flex items-center gap-3">
                          <Building2 className="h-5 w-5 text-primary" />
                          <div>
                            <p className="font-medium">ব্যাংক ট্রান্সফার</p>
                            <p className="text-sm text-muted-foreground">সরাসরি ব্যাংকে টাকা পাঠান</p>
                          </div>
                        </div>
                      </Label>
                    </div>
                  </RadioGroup>

                  {formData.payment_method === "bank_transfer" && (
                    <div className="mt-4 p-4 bg-muted rounded-lg text-sm">
                      <p className="font-medium mb-2">ব্যাংক তথ্য:</p>
                      <p>ব্যাংক: Dutch-Bangla Bank Limited</p>
                      <p>অ্যাকাউন্ট নাম: ST International</p>
                      <p>অ্যাকাউন্ট নম্বর: 1234567890</p>
                      <p>ব্রাঞ্চ: বাংলা মোটর, ঢাকা</p>
                    </div>
                  )}
                </div>

                {/* Notes */}
                <div className="bg-card border border-border rounded-lg p-6">
                  <h2 className="font-semibold text-lg mb-4">অতিরিক্ত নোট</h2>
                  <Textarea
                    value={formData.notes}
                    onChange={(e) => setFormData({ ...formData, notes: e.target.value })}
                    placeholder="বিশেষ কোনো নির্দেশনা থাকলে লিখুন..."
                    rows={3}
                  />
                </div>
              </div>

              {/* Order Summary */}
              <div className="lg:col-span-1">
                <div className="bg-card border border-border rounded-lg p-6 sticky top-24">
                  <h2 className="font-semibold text-lg mb-4">অর্ডার সারাংশ</h2>
                  
                  <div className="space-y-3 mb-4 max-h-60 overflow-y-auto">
                    {items.map((item) => (
                      <div key={item.id} className="flex gap-3 text-sm">
                        <div className="w-12 h-12 bg-muted rounded overflow-hidden shrink-0">
                          {item.image_url && (
                            <img
                              src={item.image_url}
                              alt={item.name}
                              className="w-full h-full object-cover"
                            />
                          )}
                        </div>
                        <div className="flex-1 min-w-0">
                          <p className="font-medium truncate">{item.name}</p>
                          <p className="text-muted-foreground">
                            {item.quantity} × {formatPrice(item.price)}
                          </p>
                        </div>
                        <p className="font-medium shrink-0">
                          {formatPrice(item.price * item.quantity)}
                        </p>
                      </div>
                    ))}
                  </div>

                  <div className="border-t border-border pt-4 space-y-2">
                    <div className="flex justify-between text-sm">
                      <span className="text-muted-foreground">সাবটোটাল</span>
                      <span>{formatPrice(subtotal)}</span>
                    </div>
                    <div className="flex justify-between text-sm">
                      <span className="text-muted-foreground">ডেলিভারি</span>
                      <span>{shippingCost === 0 ? "ফ্রি" : formatPrice(shippingCost)}</span>
                    </div>
                    {subtotal < 10000 && (
                      <p className="text-xs text-muted-foreground">
                        ৳১০,০০০+ অর্ডারে ফ্রি ডেলিভারি
                      </p>
                    )}
                    <div className="flex justify-between font-semibold text-lg pt-2 border-t border-border">
                      <span>মোট</span>
                      <span className="text-primary">{formatPrice(total)}</span>
                    </div>
                  </div>

                  <Button
                    type="submit"
                    variant="accent"
                    size="lg"
                    className="w-full mt-6"
                    disabled={loading}
                  >
                    {loading ? (
                      <>
                        <Loader2 className="h-4 w-4 animate-spin" />
                        অপেক্ষা করুন...
                      </>
                    ) : (
                      "অর্ডার নিশ্চিত করুন"
                    )}
                  </Button>

                  <div className="flex items-center gap-2 justify-center text-sm text-muted-foreground mt-4">
                    <ShieldCheck className="h-4 w-4" />
                    <span>নিরাপদ চেকআউট</span>
                  </div>
                </div>
              </div>
            </div>
          </form>
        </div>
      </section>
    </Layout>
  );
};

export default Checkout;
